kind: pipeline
name: default

steps:
  - name: npm ci
    image: node:8-slim
    commands:
      - npm ci

  - name: lint
    image: node:8-slim
    commands:
      - npm run lint

  - name: test
    image: node:8-slim
    commands:
      - npm run test
